[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "paris"
fs_permissions = [{ access = "read-write", path = "./" }]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
base = "${NEXT_PUBLIC_BASE_RPC_URL}"

[etherscan]
base = { key = "${BASESCAN_API_KEY}", chain = 8453, url = "https://api.basescan.org/api"  }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

