[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "paris"

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
base = "${NEXT_PUBLIC_BASE_RPC_URL}"

[etherscan]
# sepolia = { key = "${ETHERSCAN_API_KEY}", chain = 11155111, url = "https://api-sepolia.etherscan.io/api"  }
base = { key = "${BASESCAN_API_KEY}", chain = 8453, url = "https://api.basescan.org/api"  }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

