[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
base = "${BASE_RPC_URL}"

[etherscan]
sepolia = { key = "${BASESCAN_API_KEY}", chain = 84532, url = "https://api-sepolia.basescan.org/api"  }
base = { key = "${BASESCAN_API_KEY}", url = "https://api.basescan.org/api"  }


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
