/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FartherAirdrop } from "./FartherAirdrop";
export type { FartherAirdrop1 } from "./FartherAirdrop1";
