/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { FartherAirdrop__factory } from "./FartherAirdrop__factory";
export { FartherAirdrop1__factory } from "./FartherAirdrop1__factory";
